version: '3.7'

services:
  taskmgr_db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./TaskMgrDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "taskmgr"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d taskmgr" ]
      interval: 2s
      timeout: 2s
      retries: 20
    networks:
      - taskmgr_network

  taskmgr_api:
    image: taskmgr/api
    build:
      context: .
      dockerfile: TaskMgrAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DB_CONNECTION_STRING: ${TASKMGR_DB_CONNECTION_STRING}
    depends_on:
      taskmgr_db:
        condition: service_healthy
    ports:
      - '8000:80'
      - '443:443'
    networks:
      - taskmgr_network

  taskmgr_tgbot:
    image: taskmgr/tgbot
    restart: always
    build:
      context: ./TaskMgrTgBot
    environment:
      - TOKEN=${TASKMGR_TOKEN}
      - API_URL=${TASKMGR_API_URL}
    depends_on:
      - taskmgr_api
    networks:
      - taskmgr_network

volumes:
  db_volume:
  pgadmin-data:

networks:
  taskmgr_network:
    driver: bridge