version: '3.7'

services:
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - taskmgr_db
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - taskmgr_network

  taskmgr_db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./TaskMgrDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "taskmgr"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d taskmgr" ]
      interval: 2s
      timeout: 2s
      retries: 20
    networks:
      - taskmgr_network

  taskmgr_api:
    image: taskmgr/api
    build:
      context: .
      dockerfile: TaskMgrAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DB_CONNECTION_STRING: "host=taskmgr_db;port=5432;database=taskmgr;username=postgres;password=postgres"
    depends_on:
      taskmgr_db:
        condition: service_healthy
    ports:
      - '8000:80'
      - '443:443'
    networks:
      - taskmgr_network

volumes:
  db_volume:
  pgadmin-data:

networks:
  taskmgr_network:
    driver: bridge